// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projet_hopital.Data;

#nullable disable

namespace projet_hopital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105153148_AddImageUrls")]
    partial class AddImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Heart and cardiovascular system care",
                            ImageUrl = "/images/departments/cardiology.jpg",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Brain and nervous system treatment",
                            ImageUrl = "/images/departments/neurology.jpg",
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Medical care for infants, children, and adolescents",
                            ImageUrl = "/images/departments/pediatrics.jpg",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Musculoskeletal system treatment",
                            ImageUrl = "/images/departments/orthopedics.jpg",
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Skin, hair, and nail care",
                            ImageUrl = "/images/departments/dermatology.jpg",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Primary healthcare and general medical services",
                            ImageUrl = "/images/departments/general.jpg",
                            Name = "General Medicine"
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert in cardiovascular diseases with 15 years of experience",
                            ConsultationFee = 150.00m,
                            DepartmentId = 1,
                            FirstName = "Jean",
                            ImageUrl = "/images/doctors/doctor-1.jpg",
                            IsAvailable = true,
                            LastName = "Martin",
                            Specialization = "Cardiologist",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Specialized in neurological disorders and brain health",
                            ConsultationFee = 175.00m,
                            DepartmentId = 2,
                            FirstName = "Marie",
                            ImageUrl = "/images/doctors/doctor-2.jpg",
                            IsAvailable = true,
                            LastName = "Dupont",
                            Specialization = "Neurologist",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dedicated to children's health and wellness",
                            ConsultationFee = 100.00m,
                            DepartmentId = 3,
                            FirstName = "Pierre",
                            ImageUrl = "/images/doctors/doctor-3.jpg",
                            IsAvailable = true,
                            LastName = "Bernard",
                            Specialization = "Pediatrician",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Expert in bone and joint surgery",
                            ConsultationFee = 200.00m,
                            DepartmentId = 4,
                            FirstName = "Sophie",
                            ImageUrl = "/images/doctors/doctor-4.jpg",
                            IsAvailable = true,
                            LastName = "Leroy",
                            Specialization = "Orthopedic Surgeon",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Skin care specialist with expertise in various skin conditions",
                            ConsultationFee = 120.00m,
                            DepartmentId = 5,
                            FirstName = "Antoine",
                            ImageUrl = "/images/doctors/doctor-5.jpg",
                            IsAvailable = true,
                            LastName = "Moreau",
                            Specialization = "Dermatologist",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Family medicine expert providing comprehensive primary care",
                            ConsultationFee = 80.00m,
                            DepartmentId = 6,
                            FirstName = "Claire",
                            ImageUrl = "/images/doctors/doctor-6.jpg",
                            IsAvailable = true,
                            LastName = "Petit",
                            Specialization = "General Practitioner",
                            YearsOfExperience = 20
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DoctorServices");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 5
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 6
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 9
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 10
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 11
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 12
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 13
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 14
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Records the electrical activity of the heart",
                            DurationMinutes = 30,
                            ImageUrl = "/images/services/ecg.jpg",
                            IsActive = true,
                            Name = "ECG - Electrocardiogram",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Ultrasound imaging of the heart",
                            DurationMinutes = 45,
                            ImageUrl = "/images/services/echo.jpg",
                            IsActive = true,
                            Name = "Echocardiogram",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "Evaluates heart function during physical activity",
                            DurationMinutes = 60,
                            ImageUrl = "/images/services/stress-test.jpg",
                            IsActive = true,
                            Name = "Cardiac Stress Test",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Description = "Measures electrical activity in the brain",
                            DurationMinutes = 45,
                            ImageUrl = "/images/services/eeg.jpg",
                            IsActive = true,
                            Name = "EEG - Electroencephalogram",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Description = "Comprehensive assessment of nervous system function",
                            DurationMinutes = 30,
                            ImageUrl = "/images/services/neuro-exam.jpg",
                            IsActive = true,
                            Name = "Neurological Examination",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Description = "Routine health examination for children",
                            DurationMinutes = 30,
                            ImageUrl = "/images/services/child-checkup.jpg",
                            IsActive = true,
                            Name = "Well-Child Checkup",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Description = "Immunization services for children",
                            DurationMinutes = 15,
                            ImageUrl = "/images/services/vaccination.jpg",
                            IsActive = true,
                            Name = "Vaccination",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Description = "Diagnostic imaging for bones and joints",
                            DurationMinutes = 20,
                            ImageUrl = "/images/services/xray.jpg",
                            IsActive = true,
                            Name = "X-Ray Imaging",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            Description = "Rehabilitation and therapeutic exercises",
                            DurationMinutes = 60,
                            ImageUrl = "/images/services/physical-therapy.jpg",
                            IsActive = true,
                            Name = "Physical Therapy Session",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Description = "Comprehensive skin health assessment",
                            DurationMinutes = 30,
                            ImageUrl = "/images/services/skin-exam.jpg",
                            IsActive = true,
                            Name = "Skin Examination",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 5,
                            Description = "Professional acne management and treatment",
                            DurationMinutes = 45,
                            ImageUrl = "/images/services/acne-treatment.jpg",
                            IsActive = true,
                            Name = "Acne Treatment",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 6,
                            Description = "Primary care consultation and health assessment",
                            DurationMinutes = 30,
                            ImageUrl = "/images/services/consultation.jpg",
                            IsActive = true,
                            Name = "General Consultation",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 6,
                            Description = "Comprehensive yearly health examination",
                            DurationMinutes = 60,
                            ImageUrl = "/images/services/health-checkup.jpg",
                            IsActive = true,
                            Name = "Annual Health Checkup",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 6,
                            Description = "Complete blood count and chemistry panel",
                            DurationMinutes = 15,
                            ImageUrl = "/images/services/blood-test.jpg",
                            IsActive = true,
                            Name = "Blood Test Panel",
                            Price = 150.00m
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Appointments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithOne("Basket")
                        .HasForeignKey("projet_hopital.Models.Basket", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("BasketItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Basket");

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("DoctorServices")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("DoctorServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Basket");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorServices");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("DoctorServices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
