// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projet_hopital.Data;

#nullable disable

namespace projet_hopital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105153329_UpdateToFrenchWithOnlineImages")]
    partial class UpdateToFrenchWithOnlineImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soins du cœur et du système cardiovasculaire",
                            ImageUrl = "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=300",
                            Name = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Traitement du cerveau et du système nerveux",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=300",
                            Name = "Neurologie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soins médicaux pour les nourrissons, enfants et adolescents",
                            ImageUrl = "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=300",
                            Name = "Pédiatrie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traitement du système musculo-squelettique",
                            ImageUrl = "https://images.unsplash.com/photo-1579684453423-f84349ef60b0?w=300",
                            Name = "Orthopédie"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Soins de la peau, des cheveux et des ongles",
                            ImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300",
                            Name = "Dermatologie"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Soins de santé primaires et services médicaux généraux",
                            ImageUrl = "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=300",
                            Name = "Médecine Générale"
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert en maladies cardiovasculaires avec 15 ans d'expérience",
                            ConsultationFee = 150.00m,
                            DepartmentId = 1,
                            FirstName = "Jean",
                            ImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300",
                            IsAvailable = true,
                            LastName = "Martin",
                            Specialization = "Cardiologue",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Spécialisée dans les troubles neurologiques et la santé cérébrale",
                            ConsultationFee = 175.00m,
                            DepartmentId = 2,
                            FirstName = "Marie",
                            ImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300",
                            IsAvailable = true,
                            LastName = "Dupont",
                            Specialization = "Neurologue",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dédié à la santé et au bien-être des enfants",
                            ConsultationFee = 100.00m,
                            DepartmentId = 3,
                            FirstName = "Pierre",
                            ImageUrl = "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
                            IsAvailable = true,
                            LastName = "Bernard",
                            Specialization = "Pédiatre",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Expert en chirurgie osseuse et articulaire",
                            ConsultationFee = 200.00m,
                            DepartmentId = 4,
                            FirstName = "Sophie",
                            ImageUrl = "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=300",
                            IsAvailable = true,
                            LastName = "Leroy",
                            Specialization = "Chirurgien Orthopédiste",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Spécialiste des soins de la peau avec expertise dans diverses affections cutanées",
                            ConsultationFee = 120.00m,
                            DepartmentId = 5,
                            FirstName = "Antoine",
                            ImageUrl = "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300",
                            IsAvailable = true,
                            LastName = "Moreau",
                            Specialization = "Dermatologue",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Expert en médecine familiale offrant des soins primaires complets",
                            ConsultationFee = 80.00m,
                            DepartmentId = 6,
                            FirstName = "Claire",
                            ImageUrl = "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300",
                            IsAvailable = true,
                            LastName = "Petit",
                            Specialization = "Médecin Généraliste",
                            YearsOfExperience = 20
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DoctorServices");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 5
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 6
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 9
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 10
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 11
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 12
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 13
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 14
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Enregistre l'activité électrique du cœur",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
                            IsActive = true,
                            Name = "ECG - Électrocardiogramme",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Imagerie par ultrasons du cœur",
                            DurationMinutes = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400",
                            IsActive = true,
                            Name = "Échocardiogramme",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "Évalue la fonction cardiaque pendant l'activité physique",
                            DurationMinutes = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=400",
                            IsActive = true,
                            Name = "Test d'Effort Cardiaque",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Description = "Mesure l'activité électrique du cerveau",
                            DurationMinutes = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=400",
                            IsActive = true,
                            Name = "EEG - Électroencéphalogramme",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Description = "Évaluation complète de la fonction du système nerveux",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400",
                            IsActive = true,
                            Name = "Examen Neurologique",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Description = "Examen de santé de routine pour les enfants",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1551076805-e1869033e561?w=400",
                            IsActive = true,
                            Name = "Bilan de Santé Enfant",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Description = "Services d'immunisation pour les enfants",
                            DurationMinutes = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400",
                            IsActive = true,
                            Name = "Vaccination",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Description = "Imagerie diagnostique pour les os et articulations",
                            DurationMinutes = 20,
                            ImageUrl = "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=400",
                            IsActive = true,
                            Name = "Radiographie",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            Description = "Rééducation et exercices thérapeutiques",
                            DurationMinutes = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
                            IsActive = true,
                            Name = "Séance de Kinésithérapie",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Description = "Évaluation complète de la santé de la peau",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400",
                            IsActive = true,
                            Name = "Examen Dermatologique",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 5,
                            Description = "Gestion et traitement professionnel de l'acné",
                            DurationMinutes = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
                            IsActive = true,
                            Name = "Traitement de l'Acné",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 6,
                            Description = "Consultation de soins primaires et évaluation de santé",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=400",
                            IsActive = true,
                            Name = "Consultation Générale",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 6,
                            Description = "Examen de santé annuel complet",
                            DurationMinutes = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=400",
                            IsActive = true,
                            Name = "Bilan de Santé Annuel",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 6,
                            Description = "Numération formule sanguine complète et panel chimique",
                            DurationMinutes = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=400",
                            IsActive = true,
                            Name = "Bilan Sanguin Complet",
                            Price = 150.00m
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Appointments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithOne("Basket")
                        .HasForeignKey("projet_hopital.Models.Basket", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("BasketItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Basket");

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("DoctorServices")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("DoctorServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Basket");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorServices");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("DoctorServices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
