// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projet_hopital.Data;

#nullable disable

namespace projet_hopital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107184845_FixDatabaseSchema")]
    partial class FixDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("PreferredTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soins du cœur et du système cardiovasculaire",
                            ImageUrl = "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=300",
                            Name = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Traitement du cerveau et du système nerveux",
                            ImageUrl = "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=300",
                            Name = "Neurologie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soins médicaux pour les nourrissons, enfants et adolescents",
                            ImageUrl = "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=300",
                            Name = "Pédiatrie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traitement du système musculo-squelettique",
                            ImageUrl = "https://images.unsplash.com/photo-1579684453423-f84349ef60b0?w=300",
                            Name = "Orthopédie"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Soins de la peau, des cheveux et des ongles",
                            ImageUrl = "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300",
                            Name = "Dermatologie"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Soins de santé primaires et services médicaux généraux",
                            ImageUrl = "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=300",
                            Name = "Médecine Générale"
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert en maladies cardiovasculaires avec 15 ans d'expérience",
                            ConsultationFee = 450.00m,
                            DepartmentId = 1,
                            FirstName = "Yassine",
                            ImageUrl = "https://images.unsplash.com/photo-1700041785712-649e859d9909?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Lechgar",
                            Specialization = "Cardiologue",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Spécialisée dans les troubles neurologiques et la santé cérébrale",
                            ConsultationFee = 375.00m,
                            DepartmentId = 2,
                            FirstName = "Amal",
                            ImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Alawi",
                            Specialization = "Neurologue",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Dédié à la santé et au bien-être des enfants",
                            ConsultationFee = 400.00m,
                            DepartmentId = 3,
                            FirstName = "Anas",
                            ImageUrl = "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Debagh",
                            Specialization = "Pédiatre",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Expert en chirurgie osseuse et articulaire",
                            ConsultationFee = 500.00m,
                            DepartmentId = 4,
                            FirstName = "Manar",
                            ImageUrl = "https://images.unsplash.com/photo-1742436707321-33fed05590bb?q=80&w=851&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Sefawi",
                            Specialization = "Chirurgien Orthopédiste",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Spécialiste des soins de la peau avec expertise dans diverses affections cutanées",
                            ConsultationFee = 420.00m,
                            DepartmentId = 5,
                            FirstName = "Ali",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1723780925032-1ad5b130db77?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Lakhder",
                            Specialization = "Dermatologue",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Expert en médecine familiale offrant des soins primaires complets",
                            ConsultationFee = 380.00m,
                            DepartmentId = 6,
                            FirstName = "Dawoud",
                            ImageUrl = "https://images.unsplash.com/photo-1582750433449-648ed127bb54?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            IsAvailable = true,
                            LastName = "Mountasib",
                            Specialization = "Médecin Généraliste",
                            YearsOfExperience = 20
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DoctorServices");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            DoctorId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            DoctorId = 2,
                            ServiceId = 5
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 6
                        },
                        new
                        {
                            DoctorId = 3,
                            ServiceId = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            DoctorId = 4,
                            ServiceId = 9
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 10
                        },
                        new
                        {
                            DoctorId = 5,
                            ServiceId = 11
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 12
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 13
                        },
                        new
                        {
                            DoctorId = 6,
                            ServiceId = 14
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Enregistre l'activité électrique du cœur",
                            DurationMinutes = 30,
                            ImageUrl = "https://www.ramsayservices.fr/sites/default/files/styles/original/public/2025-05/iStock-1464012950%20%281%29.jpg?itok=nrlgm6-M",
                            IsActive = true,
                            Name = "ECG - Électrocardiogramme",
                            Price = 375.00m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Imagerie par ultrasons du cœur",
                            DurationMinutes = 45,
                            ImageUrl = "https://www.medicaim.com/uploads/84ed39b0-5a46-11e8-8fc5-bf61b50ce761/echocardiogramme.jpg",
                            IsActive = true,
                            Name = "Échocardiogramme",
                            Price = 550.00m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "Évalue la fonction cardiaque pendant l'activité physique",
                            DurationMinutes = 60,
                            ImageUrl = "https://sf1.topsante.com/wp-content/uploads/topsante/2023/09/maladies-coeur-choses-savoir-sur-test-effort.jpeg",
                            IsActive = true,
                            Name = "Test d'Effort Cardiaque",
                            Price = 600.00m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Description = "Mesure l'activité électrique du cerveau",
                            DurationMinutes = 45,
                            ImageUrl = "https://bolgehospitalinternational.com/wp-content/uploads/2023/11/EEG.jpg",
                            IsActive = true,
                            Name = "EEG - Électroencéphalogramme",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Description = "Évaluation complète de la fonction du système nerveux",
                            DurationMinutes = 30,
                            ImageUrl = "https://atlantabrainandspine.com/wp-content/uploads/2022/02/iStock-1254897003.jpg",
                            IsActive = true,
                            Name = "Examen Neurologique",
                            Price = 550.00m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Description = "Examen de santé de routine pour les enfants",
                            DurationMinutes = 30,
                            ImageUrl = "https://www.solimut-mutuelle.fr/wp-content/uploads/2024/08/Format-670x410-1.jpg",
                            IsActive = true,
                            Name = "Bilan de Santé Enfant",
                            Price = 480.00m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Description = "Services d'immunisation pour les enfants",
                            DurationMinutes = 15,
                            ImageUrl = "https://blogs.worldbank.org/content/dam/sites/blogs/img/detail/mgr/vaccination.png",
                            IsActive = true,
                            Name = "Vaccination",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Description = "Imagerie diagnostique pour les os et articulations",
                            DurationMinutes = 20,
                            ImageUrl = "https://images.philips.com/is/image/philipsconsumer/8801433f55664de7a17bb11400ea0b8a?extend=0,-280,0,-575&wid=1500&hei=844&fit=stretch,1&$jpglarge$",
                            IsActive = true,
                            Name = "Radiographie",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            Description = "Rééducation et exercices thérapeutiques",
                            DurationMinutes = 60,
                            ImageUrl = "https://www.centremjmedical.com/wp-content/uploads/2022/05/Medecine-Douce-Kinesitherapie-Centre-MJ-Medical-Marrakech-1.jpg",
                            IsActive = true,
                            Name = "Séance de Kinésithérapie",
                            Price = 520.00m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            Description = "Évaluation complète de la santé de la peau",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.ctfassets.net/nla4ils4bv6t/ZrA1T29UE5kaUfJhVuRjo/3907d77dae1904df0e77002f2b812aba/dermato.jpg",
                            IsActive = true,
                            Name = "Examen Dermatologique",
                            Price = 590.00m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 5,
                            Description = "Gestion et traitement professionnel de l'acné",
                            DurationMinutes = 45,
                            ImageUrl = "https://allure-derm.com/storage/2024/04/Acne-Treatment-by-Allure-Dermatology-in-Edinburg-TX.webp",
                            IsActive = true,
                            Name = "Traitement de l'Acné",
                            Price = 550.00m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 6,
                            Description = "Consultation de soins primaires et évaluation de santé",
                            DurationMinutes = 30,
                            ImageUrl = "https://www.ecotowndiagnostics.com/wp-content/uploads/2024/06/818dce83d6.jpg",
                            IsActive = true,
                            Name = "Consultation Générale",
                            Price = 560.00m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 6,
                            Description = "Examen de santé annuel complet",
                            DurationMinutes = 600,
                            ImageUrl = "https://myhealthassistance.ma/wp-content/uploads/2024/04/BandeauBilanSante-1_0.jpg",
                            IsActive = true,
                            Name = "Bilan de Santé Annuel",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 6,
                            Description = "Numération formule sanguine complète et panel chimique",
                            DurationMinutes = 15,
                            ImageUrl = "https://cdn8.futura-sciences.com/a1280/images/prise%20de%20sang.jpg",
                            IsActive = true,
                            Name = "Bilan Sanguin Complet",
                            Price = 550.00m
                        });
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("projet_hopital.Models.Appointment", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Appointments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithOne("Basket")
                        .HasForeignKey("projet_hopital.Models.Basket", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.BasketItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("BasketItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Basket");

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.DoctorService", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany("DoctorServices")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("DoctorServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.HasOne("projet_hopital.Models.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.HasOne("projet_hopital.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projet_hopital.Models.OrderItem", b =>
                {
                    b.HasOne("projet_hopital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("projet_hopital.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projet_hopital.Models.MedicalService", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("projet_hopital.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Basket");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("projet_hopital.Models.Basket", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("projet_hopital.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("projet_hopital.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorServices");
                });

            modelBuilder.Entity("projet_hopital.Models.MedicalService", b =>
                {
                    b.Navigation("BasketItems");

                    b.Navigation("DoctorServices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("projet_hopital.Models.Order", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
